// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tuontaAPI;

#nullable disable

namespace tuontaAPI.Migrations
{
    [DbContext(typeof(TuontaDbContext))]
    [Migration("20241208184010_Added Data")]
    partial class AddedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tuontaAPI.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ProfileImages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Hello, I'm John!",
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Course = "Computer Science",
                            Distance = 50,
                            Email = "johndoe@example.com",
                            Gender = "Male",
                            Hobbies = "[\"Reading\",\"Swimming\"]",
                            ProfileImages = "[\"image1.jpg\",\"image2.jpg\"]",
                            School = "Example University",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Hi, I'm Jane!",
                            Birthday = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Course = "Mathematics",
                            Distance = 30,
                            Email = "janedoe@example.com",
                            Gender = "Female",
                            Hobbies = "[\"Running\",\"Cooking\"]",
                            ProfileImages = "[\"image3.jpg\",\"image4.jpg\"]",
                            School = "Example University",
                            Username = "janedoe"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Hey, I'm Alex!",
                            Birthday = new DateTime(1995, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Course = "Physics",
                            Distance = 20,
                            Email = "alexsmith@example.com",
                            Gender = "Other",
                            Hobbies = "[\"Gaming\",\"Hiking\"]",
                            ProfileImages = "[\"image5.jpg\",\"image6.jpg\"]",
                            School = "Example University",
                            Username = "alexsmith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
